# Generated by Django 4.2.6 on 2023-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(max_length=100)),
                ('member1', models.CharField(max_length=50)),
                ('roll1', models.CharField(blank=True, max_length=20)),
                ('member2', models.CharField(max_length=50)),
                ('roll2', models.CharField(blank=True, max_length=20)),
                ('abstract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('member1', models.CharField(max_length=50)),
                ('roll1', models.CharField(blank=True, max_length=20)),
                ('member2', models.CharField(max_length=50)),
                ('roll2', models.CharField(blank=True, max_length=20)),
                ('abstract', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Circuitry',
        ),
        migrations.DeleteModel(
            name='Civiathon',
        ),
        migrations.DeleteModel(
            name='CodeClueCrew',
        ),
        migrations.DeleteModel(
            name='Mechmania',
        ),
        migrations.DeleteModel(
            name='odetocode',
        ),
        migrations.DeleteModel(
            name='PaperPresentationIT',
        ),
        migrations.DeleteModel(
            name='ProductPitching',
        ),
        migrations.RemoveField(
            model_name='projectpresentationit',
            name='timeslot',
        ),
        migrations.DeleteModel(
            name='SyntaxSmackdown',
        ),
        migrations.DeleteModel(
            name='Techtales',
        ),
        migrations.RenameField(
            model_name='ideathon',
            old_name='about',
            new_name='abstract',
        ),
        migrations.RemoveField(
            model_name='ideathon',
            name='teamsize',
        ),
        migrations.RemoveField(
            model_name='ideathon',
            name='topicname',
        ),
        migrations.DeleteModel(
            name='ProjectPresentationIT',
        ),
    ]
