# Generated by Django 4.2.6 on 2023-11-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0002_paperpresentation_projectpresentation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideathon',
            name='abstract',
        ),
    ]
