# Generated by Django 4.2.6 on 2023-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0003_remove_ideathon_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideathon',
            name='teamname',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
    ]
