# Generated by Django 4.2.6 on 2023-11-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0005_remove_ideathon_member4_remove_ideathon_roll4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('member1', models.CharField(max_length=50)),
                ('roll1', models.CharField(blank=True, max_length=20)),
                ('member2', models.CharField(max_length=50)),
                ('roll2', models.CharField(blank=True, max_length=20)),
                ('member3', models.CharField(max_length=50)),
                ('roll3', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
