# Generated by Django 4.2.6 on 2023-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productdesc',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
