# Generated by Django 4.2.6 on 2023-11-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0007_product_productdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpresentation',
            name='stream',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
