# Generated by Django 4.2.6 on 2023-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0008_projectpresentation_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpresentation',
            name='stream',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
    ]
