# Generated by Django 4.2.6 on 2023-11-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0009_paperpresentation_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productdesc',
            new_name='contact',
        ),
    ]
