# Generated by Django 4.2.6 on 2023-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0010_rename_productdesc_product_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideathon',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
