# Generated by Django 4.2.6 on 2023-11-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0011_ideathon_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(default='As'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
