# Generated by Django 4.2.6 on 2023-11-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0012_product_about_alter_product_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='member3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='roll3',
        ),
    ]
