# Generated by Django 4.2.6 on 2023-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0014_paperpresentation_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpresentation',
            name='contact',
            field=models.CharField(max_length=40),
        ),
    ]
