# Generated by Django 4.2.6 on 2023-11-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0015_alter_projectpresentation_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperpresentation',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='projectpresentation',
            name='contact',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
