# Generated by Django 4.2.6 on 2023-11-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphamain', '0017_totalregistration_delete_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalregistration',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
